name: Deploy to production server

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: atomrem/codefrost-discord-motivation-bot:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy to DO Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.DROPLET_IP }}
          username: ${{ vars.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/discord-motivation-bot
            docker pull atomrem/codefrost-discord-motivation-bot:latest
            docker stop codefrost-discord-motivation-bot
            docker rm codefrost-discord-motivation-bot
            
            docker run -d --name codefrost-discord-motivation-bot \
            --env-file .env \
            -v $PWD/tasks.txt:/app/tasks.txt \
            atomrem/codefrost-discord-motivation-bot:latest
